#!/bin/bash

URL="http://localhost:8000"

echo "Running Health Check..."

sleep 10

STATUS=$(curl -o /dev/null -s -w "%{http_code}" $URL)

if [ "$STATUS" == "200" ]; then
    echo "Health Check Passed."
    exit 0
else
    echo "Health Check Failed."
    exit 1
fi
